### ISSUE TITLE
Dataset files do not exist in ebm_prior.py, unet.py, and snet.py

### ISSUE THREAD

**Issue by zhouqp631** [akarshp28/EIT-EBM#1]
Hello, thank you so much for sharing the code. I have some questions about the code.

 ---
1. `PrepareData_single.m` and `PrepareData_multi.m` can generate many .mat files
---
2. For `ebm_score_matching.py`: How can I construct the `multisigma_ebm_128_no_circle_v2.pickle` file? What is `omega_mask.npy`?
    ```python
    with open('../../dataset/multisigma_ebm_128_no_circle_v2.pickle', 'rb') as handle:
        all_data = pickle.load(handle)
   
    mask = np.load('./omega_mask.npy').astype(np.float32)
    ```
---
3. For `unet.py` and `snet.py`: What is multi_phantom_1_128.npy?
    ```python
    # ppath = '../dataset/multi_phantom_1_128.npy'
    # ppath = '../dataset/multi_phantom_11_128.npy'
    # ppath = '../dataset/multi_phantom_3_128.npy'
    # ppath = '../dataset/multi_phantom_4_128.npy'
    ```

**Comment by akarshp28** [comment]
Hello, thank you for using our work. This work has been discontinued hence, the response is slow. Sincere apologies for the long delay.

Question 1) You need to PrepareData_single.m for single phantoms used for forward and inverse solving. This creates a .mat file that is later read by script in question 3 below for final assembled data. While PrepareData_multi.m creates many phantoms at random locations and later uses script in question 2 below for final assembled data for EBM training,

Question 2) You can find the EBM dataset creation scripts below:
https://github.com/akarshp28/EIT-EBM/blob/main/data_creation/sigma_data_prep.py
Omega mask is the mask that creates the domain points inside circle, without boundary points.

Question 3) I have uploaded new code below to create these single phantoms:
https://github.com/akarshp28/EIT-EBM/blob/main/data_creation/multiexp_dataprep.ipynb

Best,

Akarsh
